<?php

/**
 * Base static class for performing query and update operations on the 'job' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Aug 12 12:14:21 2009
 *
 * @package    lib.model.om
 */
abstract class BaseJobPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'job';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Job';

	/** The total number of columns. */
	const NUM_COLUMNS = 32;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'job.ID';

	/** the column name for the PROJECT_ID field */
	const PROJECT_ID = 'job.PROJECT_ID';

	/** the column name for the PUBLICATION_ID field */
	const PUBLICATION_ID = 'job.PUBLICATION_ID';

	/** the column name for the STATUS_ID field */
	const STATUS_ID = 'job.STATUS_ID';

	/** the column name for the EVENT field */
	const EVENT = 'job.EVENT';

	/** the column name for the DATE field */
	const DATE = 'job.DATE';

	/** the column name for the START_TIME field */
	const START_TIME = 'job.START_TIME';

	/** the column name for the END_TIME field */
	const END_TIME = 'job.END_TIME';

	/** the column name for the DUE_DATE field */
	const DUE_DATE = 'job.DUE_DATE';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'job.CREATED_AT';

	/** the column name for the STREET field */
	const STREET = 'job.STREET';

	/** the column name for the CITY field */
	const CITY = 'job.CITY';

	/** the column name for the STATE field */
	const STATE = 'job.STATE';

	/** the column name for the ZIP field */
	const ZIP = 'job.ZIP';

	/** the column name for the CONTACT_NAME field */
	const CONTACT_NAME = 'job.CONTACT_NAME';

	/** the column name for the CONTACT_EMAIL field */
	const CONTACT_EMAIL = 'job.CONTACT_EMAIL';

	/** the column name for the CONTACT_PHONE field */
	const CONTACT_PHONE = 'job.CONTACT_PHONE';

	/** the column name for the NOTES field */
	const NOTES = 'job.NOTES';

	/** the column name for the ESTIMATE field */
	const ESTIMATE = 'job.ESTIMATE';

	/** the column name for the ACCT_NUM field */
	const ACCT_NUM = 'job.ACCT_NUM';

	/** the column name for the DEPT_ID field */
	const DEPT_ID = 'job.DEPT_ID';

	/** the column name for the GRANT_ID field */
	const GRANT_ID = 'job.GRANT_ID';

	/** the column name for the OTHER field */
	const OTHER = 'job.OTHER';

	/** the column name for the QUES1 field */
	const QUES1 = 'job.QUES1';

	/** the column name for the QUES2 field */
	const QUES2 = 'job.QUES2';

	/** the column name for the QUES3 field */
	const QUES3 = 'job.QUES3';

	/** the column name for the SLUG field */
	const SLUG = 'job.SLUG';

	/** the column name for the PHOTO_TYPE field */
	const PHOTO_TYPE = 'job.PHOTO_TYPE';

	/** the column name for the PROCESSING field */
	const PROCESSING = 'job.PROCESSING';

	/** the column name for the G_CAL_ID field */
	const G_CAL_ID = 'job.G_CAL_ID';

	/** the column name for the G_CAL_ID_CUSTOM field */
	const G_CAL_ID_CUSTOM = 'job.G_CAL_ID_CUSTOM';

	/** the column name for the G_CAL_ID_CUSTOM_URL field */
	const G_CAL_ID_CUSTOM_URL = 'job.G_CAL_ID_CUSTOM_URL';

	/**
	 * An identiy map to hold any loaded instances of Job objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Job[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'ProjectId', 'PublicationId', 'StatusId', 'Event', 'Date', 'StartTime', 'EndTime', 'DueDate', 'CreatedAt', 'Street', 'City', 'State', 'Zip', 'ContactName', 'ContactEmail', 'ContactPhone', 'Notes', 'Estimate', 'AcctNum', 'DeptId', 'GrantId', 'Other', 'Ques1', 'Ques2', 'Ques3', 'Slug', 'PhotoType', 'Processing', 'GCalId', 'GCalIdCustom', 'GCalIdCustomUrl', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'projectId', 'publicationId', 'statusId', 'event', 'date', 'startTime', 'endTime', 'dueDate', 'createdAt', 'street', 'city', 'state', 'zip', 'contactName', 'contactEmail', 'contactPhone', 'notes', 'estimate', 'acctNum', 'deptId', 'grantId', 'other', 'ques1', 'ques2', 'ques3', 'slug', 'photoType', 'processing', 'gCalId', 'gCalIdCustom', 'gCalIdCustomUrl', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::PROJECT_ID, self::PUBLICATION_ID, self::STATUS_ID, self::EVENT, self::DATE, self::START_TIME, self::END_TIME, self::DUE_DATE, self::CREATED_AT, self::STREET, self::CITY, self::STATE, self::ZIP, self::CONTACT_NAME, self::CONTACT_EMAIL, self::CONTACT_PHONE, self::NOTES, self::ESTIMATE, self::ACCT_NUM, self::DEPT_ID, self::GRANT_ID, self::OTHER, self::QUES1, self::QUES2, self::QUES3, self::SLUG, self::PHOTO_TYPE, self::PROCESSING, self::G_CAL_ID, self::G_CAL_ID_CUSTOM, self::G_CAL_ID_CUSTOM_URL, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'project_id', 'publication_id', 'status_id', 'event', 'date', 'start_time', 'end_time', 'due_date', 'created_at', 'street', 'city', 'state', 'zip', 'contact_name', 'contact_email', 'contact_phone', 'notes', 'estimate', 'acct_num', 'dept_id', 'grant_id', 'other', 'ques1', 'ques2', 'ques3', 'slug', 'photo_type', 'processing', 'g_cal_id', 'g_cal_id_custom', 'g_cal_id_custom_url', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'ProjectId' => 1, 'PublicationId' => 2, 'StatusId' => 3, 'Event' => 4, 'Date' => 5, 'StartTime' => 6, 'EndTime' => 7, 'DueDate' => 8, 'CreatedAt' => 9, 'Street' => 10, 'City' => 11, 'State' => 12, 'Zip' => 13, 'ContactName' => 14, 'ContactEmail' => 15, 'ContactPhone' => 16, 'Notes' => 17, 'Estimate' => 18, 'AcctNum' => 19, 'DeptId' => 20, 'GrantId' => 21, 'Other' => 22, 'Ques1' => 23, 'Ques2' => 24, 'Ques3' => 25, 'Slug' => 26, 'PhotoType' => 27, 'Processing' => 28, 'GCalId' => 29, 'GCalIdCustom' => 30, 'GCalIdCustomUrl' => 31, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'projectId' => 1, 'publicationId' => 2, 'statusId' => 3, 'event' => 4, 'date' => 5, 'startTime' => 6, 'endTime' => 7, 'dueDate' => 8, 'createdAt' => 9, 'street' => 10, 'city' => 11, 'state' => 12, 'zip' => 13, 'contactName' => 14, 'contactEmail' => 15, 'contactPhone' => 16, 'notes' => 17, 'estimate' => 18, 'acctNum' => 19, 'deptId' => 20, 'grantId' => 21, 'other' => 22, 'ques1' => 23, 'ques2' => 24, 'ques3' => 25, 'slug' => 26, 'photoType' => 27, 'processing' => 28, 'gCalId' => 29, 'gCalIdCustom' => 30, 'gCalIdCustomUrl' => 31, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::PROJECT_ID => 1, self::PUBLICATION_ID => 2, self::STATUS_ID => 3, self::EVENT => 4, self::DATE => 5, self::START_TIME => 6, self::END_TIME => 7, self::DUE_DATE => 8, self::CREATED_AT => 9, self::STREET => 10, self::CITY => 11, self::STATE => 12, self::ZIP => 13, self::CONTACT_NAME => 14, self::CONTACT_EMAIL => 15, self::CONTACT_PHONE => 16, self::NOTES => 17, self::ESTIMATE => 18, self::ACCT_NUM => 19, self::DEPT_ID => 20, self::GRANT_ID => 21, self::OTHER => 22, self::QUES1 => 23, self::QUES2 => 24, self::QUES3 => 25, self::SLUG => 26, self::PHOTO_TYPE => 27, self::PROCESSING => 28, self::G_CAL_ID => 29, self::G_CAL_ID_CUSTOM => 30, self::G_CAL_ID_CUSTOM_URL => 31, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'project_id' => 1, 'publication_id' => 2, 'status_id' => 3, 'event' => 4, 'date' => 5, 'start_time' => 6, 'end_time' => 7, 'due_date' => 8, 'created_at' => 9, 'street' => 10, 'city' => 11, 'state' => 12, 'zip' => 13, 'contact_name' => 14, 'contact_email' => 15, 'contact_phone' => 16, 'notes' => 17, 'estimate' => 18, 'acct_num' => 19, 'dept_id' => 20, 'grant_id' => 21, 'other' => 22, 'ques1' => 23, 'ques2' => 24, 'ques3' => 25, 'slug' => 26, 'photo_type' => 27, 'processing' => 28, 'g_cal_id' => 29, 'g_cal_id_custom' => 30, 'g_cal_id_custom_url' => 31, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new JobMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. JobPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(JobPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(JobPeer::ID);

		$criteria->addSelectColumn(JobPeer::PROJECT_ID);

		$criteria->addSelectColumn(JobPeer::PUBLICATION_ID);

		$criteria->addSelectColumn(JobPeer::STATUS_ID);

		$criteria->addSelectColumn(JobPeer::EVENT);

		$criteria->addSelectColumn(JobPeer::DATE);

		$criteria->addSelectColumn(JobPeer::START_TIME);

		$criteria->addSelectColumn(JobPeer::END_TIME);

		$criteria->addSelectColumn(JobPeer::DUE_DATE);

		$criteria->addSelectColumn(JobPeer::CREATED_AT);

		$criteria->addSelectColumn(JobPeer::STREET);

		$criteria->addSelectColumn(JobPeer::CITY);

		$criteria->addSelectColumn(JobPeer::STATE);

		$criteria->addSelectColumn(JobPeer::ZIP);

		$criteria->addSelectColumn(JobPeer::CONTACT_NAME);

		$criteria->addSelectColumn(JobPeer::CONTACT_EMAIL);

		$criteria->addSelectColumn(JobPeer::CONTACT_PHONE);

		$criteria->addSelectColumn(JobPeer::NOTES);

		$criteria->addSelectColumn(JobPeer::ESTIMATE);

		$criteria->addSelectColumn(JobPeer::ACCT_NUM);

		$criteria->addSelectColumn(JobPeer::DEPT_ID);

		$criteria->addSelectColumn(JobPeer::GRANT_ID);

		$criteria->addSelectColumn(JobPeer::OTHER);

		$criteria->addSelectColumn(JobPeer::QUES1);

		$criteria->addSelectColumn(JobPeer::QUES2);

		$criteria->addSelectColumn(JobPeer::QUES3);

		$criteria->addSelectColumn(JobPeer::SLUG);

		$criteria->addSelectColumn(JobPeer::PHOTO_TYPE);

		$criteria->addSelectColumn(JobPeer::PROCESSING);

		$criteria->addSelectColumn(JobPeer::G_CAL_ID);

		$criteria->addSelectColumn(JobPeer::G_CAL_ID_CUSTOM);

		$criteria->addSelectColumn(JobPeer::G_CAL_ID_CUSTOM_URL);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(JobPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Job
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = JobPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return JobPeer::populateObjects(JobPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJobPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			JobPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Job $value A Job object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Job $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Job object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Job) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Job object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Job Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = JobPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = JobPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				JobPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Publication table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinPublication(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(JobPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Project table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinProject(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(JobPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Status table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinStatus(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(JobPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related PhotoTypeRelatedByPhotoType table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinPhotoTypeRelatedByPhotoType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(JobPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Job objects pre-filled with their Publication objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Job objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinPublication(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseJobPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		JobPeer::addSelectColumns($c);
		$startcol = (JobPeer::NUM_COLUMNS - JobPeer::NUM_LAZY_LOAD_COLUMNS);
		PublicationPeer::addSelectColumns($c);

		$c->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = JobPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = JobPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				JobPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = PublicationPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = PublicationPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = PublicationPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					PublicationPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Job) to $obj2 (Publication)
				$obj2->addJob($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Job objects pre-filled with their Project objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Job objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinProject(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		JobPeer::addSelectColumns($c);
		$startcol = (JobPeer::NUM_COLUMNS - JobPeer::NUM_LAZY_LOAD_COLUMNS);
		ProjectPeer::addSelectColumns($c);

		$c->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = JobPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = JobPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				JobPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ProjectPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ProjectPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ProjectPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ProjectPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Job) to $obj2 (Project)
				$obj2->addJob($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Job objects pre-filled with their Status objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Job objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinStatus(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		JobPeer::addSelectColumns($c);
		$startcol = (JobPeer::NUM_COLUMNS - JobPeer::NUM_LAZY_LOAD_COLUMNS);
		StatusPeer::addSelectColumns($c);

		$c->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = JobPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = JobPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				JobPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = StatusPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = StatusPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = StatusPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					StatusPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Job) to $obj2 (Status)
				$obj2->addJob($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Job objects pre-filled with their PhotoType objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Job objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinPhotoTypeRelatedByPhotoType(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		JobPeer::addSelectColumns($c);
		$startcol = (JobPeer::NUM_COLUMNS - JobPeer::NUM_LAZY_LOAD_COLUMNS);
		PhotoTypePeer::addSelectColumns($c);

		$c->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = JobPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = JobPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				JobPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = PhotoTypePeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = PhotoTypePeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = PhotoTypePeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					PhotoTypePeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Job) to $obj2 (PhotoType)
				$obj2->addJob($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(JobPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);
		$criteria->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);
		$criteria->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);
		$criteria->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Job objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Job objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseJobPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		JobPeer::addSelectColumns($c);
		$startcol2 = (JobPeer::NUM_COLUMNS - JobPeer::NUM_LAZY_LOAD_COLUMNS);

		PublicationPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (PublicationPeer::NUM_COLUMNS - PublicationPeer::NUM_LAZY_LOAD_COLUMNS);

		ProjectPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ProjectPeer::NUM_COLUMNS - ProjectPeer::NUM_LAZY_LOAD_COLUMNS);

		StatusPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (StatusPeer::NUM_COLUMNS - StatusPeer::NUM_LAZY_LOAD_COLUMNS);

		PhotoTypePeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (PhotoTypePeer::NUM_COLUMNS - PhotoTypePeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);
		$c->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);
		$c->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);
		$c->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = JobPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = JobPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				JobPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Publication rows

			$key2 = PublicationPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = PublicationPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = PublicationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					PublicationPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Job) to the collection in $obj2 (Publication)
				$obj2->addJob($obj1);
			} // if joined row not null

			// Add objects for joined Project rows

			$key3 = ProjectPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = ProjectPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = ProjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ProjectPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Job) to the collection in $obj3 (Project)
				$obj3->addJob($obj1);
			} // if joined row not null

			// Add objects for joined Status rows

			$key4 = StatusPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = StatusPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = StatusPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					StatusPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Job) to the collection in $obj4 (Status)
				$obj4->addJob($obj1);
			} // if joined row not null

			// Add objects for joined PhotoType rows

			$key5 = PhotoTypePeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = PhotoTypePeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$omClass = PhotoTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					PhotoTypePeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (Job) to the collection in $obj5 (PhotoType)
				$obj5->addJob($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Publication table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptPublication(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);
				$criteria->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);
				$criteria->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Project table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptProject(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);
				$criteria->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);
				$criteria->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Status table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptStatus(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);
				$criteria->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);
				$criteria->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related PhotoTypeRelatedByPhotoType table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptPhotoTypeRelatedByPhotoType(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			JobPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);
				$criteria->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);
				$criteria->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseJobPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Job objects pre-filled with all related objects except Publication.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Job objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptPublication(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseJobPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		JobPeer::addSelectColumns($c);
		$startcol2 = (JobPeer::NUM_COLUMNS - JobPeer::NUM_LAZY_LOAD_COLUMNS);

		ProjectPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (ProjectPeer::NUM_COLUMNS - ProjectPeer::NUM_LAZY_LOAD_COLUMNS);

		StatusPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (StatusPeer::NUM_COLUMNS - StatusPeer::NUM_LAZY_LOAD_COLUMNS);

		PhotoTypePeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (PhotoTypePeer::NUM_COLUMNS - PhotoTypePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);
				$c->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);
				$c->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = JobPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = JobPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				JobPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Project rows

				$key2 = ProjectPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ProjectPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = ProjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ProjectPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Job) to the collection in $obj2 (Project)
				$obj2->addJob($obj1);

			} // if joined row is not null

				// Add objects for joined Status rows

				$key3 = StatusPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = StatusPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = StatusPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					StatusPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Job) to the collection in $obj3 (Status)
				$obj3->addJob($obj1);

			} // if joined row is not null

				// Add objects for joined PhotoType rows

				$key4 = PhotoTypePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PhotoTypePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = PhotoTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PhotoTypePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Job) to the collection in $obj4 (PhotoType)
				$obj4->addJob($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Job objects pre-filled with all related objects except Project.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Job objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptProject(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		JobPeer::addSelectColumns($c);
		$startcol2 = (JobPeer::NUM_COLUMNS - JobPeer::NUM_LAZY_LOAD_COLUMNS);

		PublicationPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (PublicationPeer::NUM_COLUMNS - PublicationPeer::NUM_LAZY_LOAD_COLUMNS);

		StatusPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (StatusPeer::NUM_COLUMNS - StatusPeer::NUM_LAZY_LOAD_COLUMNS);

		PhotoTypePeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (PhotoTypePeer::NUM_COLUMNS - PhotoTypePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);
				$c->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);
				$c->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = JobPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = JobPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				JobPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Publication rows

				$key2 = PublicationPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = PublicationPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = PublicationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					PublicationPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Job) to the collection in $obj2 (Publication)
				$obj2->addJob($obj1);

			} // if joined row is not null

				// Add objects for joined Status rows

				$key3 = StatusPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = StatusPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = StatusPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					StatusPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Job) to the collection in $obj3 (Status)
				$obj3->addJob($obj1);

			} // if joined row is not null

				// Add objects for joined PhotoType rows

				$key4 = PhotoTypePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PhotoTypePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = PhotoTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PhotoTypePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Job) to the collection in $obj4 (PhotoType)
				$obj4->addJob($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Job objects pre-filled with all related objects except Status.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Job objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptStatus(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		JobPeer::addSelectColumns($c);
		$startcol2 = (JobPeer::NUM_COLUMNS - JobPeer::NUM_LAZY_LOAD_COLUMNS);

		PublicationPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (PublicationPeer::NUM_COLUMNS - PublicationPeer::NUM_LAZY_LOAD_COLUMNS);

		ProjectPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ProjectPeer::NUM_COLUMNS - ProjectPeer::NUM_LAZY_LOAD_COLUMNS);

		PhotoTypePeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (PhotoTypePeer::NUM_COLUMNS - PhotoTypePeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);
				$c->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);
				$c->addJoin(array(JobPeer::PHOTO_TYPE,), array(PhotoTypePeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = JobPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = JobPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				JobPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Publication rows

				$key2 = PublicationPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = PublicationPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = PublicationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					PublicationPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Job) to the collection in $obj2 (Publication)
				$obj2->addJob($obj1);

			} // if joined row is not null

				// Add objects for joined Project rows

				$key3 = ProjectPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ProjectPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ProjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ProjectPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Job) to the collection in $obj3 (Project)
				$obj3->addJob($obj1);

			} // if joined row is not null

				// Add objects for joined PhotoType rows

				$key4 = PhotoTypePeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = PhotoTypePeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = PhotoTypePeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					PhotoTypePeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Job) to the collection in $obj4 (PhotoType)
				$obj4->addJob($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Job objects pre-filled with all related objects except PhotoTypeRelatedByPhotoType.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Job objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptPhotoTypeRelatedByPhotoType(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		JobPeer::addSelectColumns($c);
		$startcol2 = (JobPeer::NUM_COLUMNS - JobPeer::NUM_LAZY_LOAD_COLUMNS);

		PublicationPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (PublicationPeer::NUM_COLUMNS - PublicationPeer::NUM_LAZY_LOAD_COLUMNS);

		ProjectPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (ProjectPeer::NUM_COLUMNS - ProjectPeer::NUM_LAZY_LOAD_COLUMNS);

		StatusPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (StatusPeer::NUM_COLUMNS - StatusPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(JobPeer::PUBLICATION_ID,), array(PublicationPeer::ID,), $join_behavior);
				$c->addJoin(array(JobPeer::PROJECT_ID,), array(ProjectPeer::ID,), $join_behavior);
				$c->addJoin(array(JobPeer::STATUS_ID,), array(StatusPeer::ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = JobPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = JobPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = JobPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				JobPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Publication rows

				$key2 = PublicationPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = PublicationPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = PublicationPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					PublicationPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Job) to the collection in $obj2 (Publication)
				$obj2->addJob($obj1);

			} // if joined row is not null

				// Add objects for joined Project rows

				$key3 = ProjectPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = ProjectPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = ProjectPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					ProjectPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Job) to the collection in $obj3 (Project)
				$obj3->addJob($obj1);

			} // if joined row is not null

				// Add objects for joined Status rows

				$key4 = StatusPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = StatusPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = StatusPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					StatusPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Job) to the collection in $obj4 (Status)
				$obj4->addJob($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return JobPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Job or Criteria object.
	 *
	 * @param      mixed $values Criteria or Job object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJobPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseJobPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Job object
		}

		if ($criteria->containsKey(JobPeer::ID) && $criteria->keyContainsValue(JobPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.JobPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseJobPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Job or Criteria object.
	 *
	 * @param      mixed $values Criteria or Job object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseJobPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseJobPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(JobPeer::ID);
			$selectCriteria->add(JobPeer::ID, $criteria->remove(JobPeer::ID), $comparison);

		} else { // $values is Job object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseJobPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseJobPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the job table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(JobPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Job or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Job object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			JobPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Job) {
			// invalidate the cache for this single object
			JobPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(JobPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				JobPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Job object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Job $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Job $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(JobPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(JobPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(JobPeer::DATABASE_NAME, JobPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = JobPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Job
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = JobPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(JobPeer::DATABASE_NAME);
		$criteria->add(JobPeer::ID, $pk);

		$v = JobPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(JobPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(JobPeer::DATABASE_NAME);
			$criteria->add(JobPeer::ID, $pks, Criteria::IN);
			$objs = JobPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseJobPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the JobPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the JobPeer class:
//
// Propel::getDatabaseMap(JobPeer::DATABASE_NAME)->addTableBuilder(JobPeer::TABLE_NAME, JobPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseJobPeer::DATABASE_NAME)->addTableBuilder(BaseJobPeer::TABLE_NAME, BaseJobPeer::getMapBuilder());

