# default values
all:
  sf_guard_plugin:
    check_password_callable: [LDAPAuth, checkLDAPPassword]
    success_signin_url: welcome/redirect
  ldap_server: ldaps://ldap.tufts.edu/
  gmap_key: ABQIAAAA_6icK9WzMbH5eGCPpoZKHhQ2s80LQuI1NckErksMVT-ro0hA4hSJVIpkoZUajXHvLWpvvpsiV-qO8w
  gcal_user: contact@setfive.com
  gcal_password: tuftsphoto
  job_status:
    pending: 1
    accepted: 2
    completed: 3
    delivered: 4
    invoiced: 5
    paid: 6
    archived: 7
  project_list:
    default_view: 1
  user_type:
    admin: 1
    client: 2
    photographer: 3
    user: 4
  items_per_page: 20
  log_type:
    create: 1
    update: 2
    delete: 3
    add_photographer: 4
    add_client: 5
    remove_client: 6
    remove_photographer: 7
    add_tag: 8
    remove_tag: 9
    move_to_project: 10
    change_status: 11
    email: 12
  photoshelter_public_key: config/photoshelterpublic.pem
  tufts_private_key: config/privatekey.pem
