# default values
all:
  sf_guard_plugin:
    check_password_callable: [LDAPAuth, checkLDAPPassword]
    success_signin_url: @welcome_loggedin
  job_status:
    pending: 1
    accepted: 2
    completed: 3
    delivered: 4
    invoiced: 5
    paid: 6
    archived: 7
  project_list:
    default_view: 1
  user_type:
    admin: 1
    client: 2
    photographer: 3
    user: 4
  items_per_page: 20