################################################
# projects
################################################
project_view:
  url: /project/view/:slug
  class:    sfPropelRoute
  param: { module: project, action: view }
  options: { model: Project, type: object }
  requirements: {slug: \w+ }
project_list:
  url: /project/list
  param: { module: project, action: list }
project_create:
  url: /project/create
  param: { module: project, action: create }
project_autocomplete:
  url: /project/autocomplete
  param: { module: project, action: autocomplete }

################################################
# jobs
################################################
job_create:
  url: /job/create
  param: { module: job, action: create }
job_success:
  url: /job/success
  param: { module: job, action: success }
job_show:
  url: /job/show/:slug
  class:    sfPropelRoute
  param: { module: job, action: show }
  options: { model: Job, type: object }
  requirements: {slug: \w+ }
job_edit:
  url: /job/edit
  param: { module: job, action: edit }
job_list:
  url: /job/list/Pending
  param: { module: job, action: list }
job_list_by:
  url: /job/list/:state
  class:    sfPropelRoute
  param: { module: job, action: list }
  options: { model: Status, type: object }
  requirements: {slug: \w+ }
job_move:
  url: /job/move
  param: { module: job, action: move }
job_addto_project: 
  url: /job/add/project
  param: { module: job, action: addProject }
job_add_client:
  url: /job/add/client
  param: { module: job, action: addClient }
job_remove_client:
  url: /job/remove/client
  param: { module: job, action: removeClient }
job_add_photographer:
  url: /job/add/photographer
  param: { module: job, action: addPhotographer }
job_remove_photographer:
  url: /job/remove/photographer
  param: { module: job, action: removePhotographer }
job_view_notes:
  url: /job/view/notes/:slug
  class:    sfPropelRoute
  param: { module: job, action: viewNotes }
  options: { model: Job, type: object }
  requirements: {slug: \w+ }
job_diff_notes:
  url: /job/view/notes/diff
  param: { module: job, action: diffNotes }

################################################
# photographer
################################################
photographer_list:
  url: /photographer/list
  param: { module: photographer, action: list }
photographer_view:
  url: /photographer/view/:slug
  param: { module: photographer, action: show }
  class:    sfPropelRoute
  options: { model: Photographer, type: object }
  requirements: {slug: \w+ }
photographer_edit:
  url: /photographer/edit
  param: { module: photographer, action: edit }
photographer_view_jobs:
  url: /photographer/view/jobs/:slug
  class:    sfPropelRoute
  param: { module: photographer, action: viewJobs }
  options: { model: Photographer, type: object }
  requirements: {slug: \w+ }

################################################
# client
################################################
client_list:
  url: /client/list
  param: { module: client, action: list }
client_view:
  url: /client/view/:slug
  param: { module: client, action: show }
  class:    sfPropelRoute
  options: { model: Client, type: object }
  requirements: {slug: \w+ }
client_edit:
  url: /client/edit
  param: { module: client, action: edit }
client_view_jobs:
  url: /client/view/jobs/:slug
  class:    sfPropelRoute
  param: { module: client, action: viewJobs }
  options: { model: Client, type: object }
  requirements: {slug: \w+ }

################################################
# tags
################################################
job_add_tag:
  url: /job/tag
  param: { module: job, action: addTag }
job_remove_tag:
  url: /job/tag/delete
  param: { module: job, action: removeTag }
job_listby_tag:
  url: /tag/list/:slug
  class:    sfPropelRoute
  param: { module: tag, action: list }
  options: { model: Tag, type: object }
  requirements: {name: \w+ }
################################################
# autocompletes
################################################

tag_autocomplete:
  url: /tag/autocomplete
  param: { module: tag, action: autocomplete }
client_autocomplete:
  url: /client/autocomplete
  param: { module: client, action: autocomplete }
photographer_autocomplete:
  url: /photographer/autocomplete
  param: { module: photographer, action: autocomplete }
job_autocomplete:
  url: /job/autocomplete
  param: { module: job, action: autocomplete }
  
################################################
# search
################################################
job_search:
  url: /job/search
  param: { module: search, action: job }

advanced_search:
  url: /search/advanced
  param: { module: search, action: advanced }

view_log:
  url: /log/view
  param: { module: log, action: view }

################################################
# misc login and redirect routes
################################################

# where you go after you log in succesfully
welcome_loggedin:
  url: /home/
  param: { module: welcome, action: redirect }

# sfguard
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
################################################
# default rules
################################################

homepage:
  url:   /
  param: { module: welcome, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
################################################
