<?php
// auto-generated by sfSecurityConfigHandler
// date: 2009/03/01 18:00:10
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
